// lib/components/time/Clock.tsx
import AnalogClock from './AnalogClock';
import DigitalClock from './DigitalClock';
import styled from '@emotion/styled';
import { useState } from 'react';

const UnstyledButton = styled('button')({
  outline: 'none',
  border: 'none',
  backgroundColor: 'transparent',
});

export default function Clock({ hr, min }: { hr: string; min: string }): JSX.Element {
  const [view, setView] = useState<'digital' | 'analog'>('digital');

  return (
    <UnstyledButton type="button" onClick={() => setView(view === 'digital' ? 'analog' : 'digital')}>
      {view === 'analog' ? (
        <AnalogClock size="200" hour={parseInt(hr)} minute={parseInt(min)} />
      ) : (
        <DigitalClock size="200" hour={hr} minute={min} />
      )}
    </UnstyledButton>
  );
}

// src/lib/time/components/Clock.svelte
<script lang="ts">
  import AnalogClock from '$common/components/AnalogClock.svelte';
  import DigitalClock from '$common/components/DigitalClock.svelte';
  import { toggleStore } from '$common/stores';

  export let size = 700;
  export let hour = 6;
  export let minute = 16;
  const view = toggleStore('analog', 'digital');
</script>

<button on:click={view.toggle}>
  {#if $view === 'analog'}
    <AnalogClock {size} {hour} {minute} />
  {:else}
    <DigitalClock {size} {hour} {minute} />
  {/if}
</button>

<style>
  button {
    outline: none;
    border: none;
    background-color: transparanet;
  }
</style>
