// src/lib/common/components/DigitalClock.svelte
<script lang="ts">
  export let size = 700;
  export let hour = 6;
  export let minute = 16;

  const hr = hour === 0 ? '--' : hour < 10 ? `0${hour}` : hour;
  const min = minute === 0 ? '00' : minute < 10 ? `0${minute}` : minute;
</script>

<div class="digitalClock" style="height: {size}px; width: {size}px; font-size: {size / 4.5}px">
  {hr}:{min}
</div>

<style>
  .digitalClock {
    display: grid;
    place-items: center;
    font-family: Digital;
    color: var(--primary2);
  }
</style>

// lib/components/time/DigitalClock.tsx
import styled from '@emotion/styled';

const DigitalClockStyled = styled('div')(({ theme, size }) => ({
  display: 'grid',
  placeItems: 'center',
  height: `${size}px`,
  width: `${size}px`,
  fontFamily: 'Digital',
  color: theme.palette.primary.main,
  fontSize: size / 5,
}));

export default function DigitalClock({
  size = '500',
  hour,
  minute,
}: {
  size?: string;
  hour: string;
  minute: string;
}): JSX.Element | null {
  const hr = hour === '' ? '--' : hour.length === 1 ? `0${hour}` : hour;
  const min = minute === '' ? '--' : minute.length === 1 ? `0${minute}` : minute;

  return (
    <DigitalClockStyled size={size}>
      {hr}:{min}
    </DigitalClockStyled>
  );
}
