// src/lib/number/components/Goal.svelte
<script lang="ts">
  export let numOrHan: 'num' | 'han';
  export let koreanAriaLabel: string;
  export let englishAriaLabel: string;
  export let tabindex = 0;
</script>

<h1
  aria-label={numOrHan === 'han' ? koreanAriaLabel : englishAriaLabel}
  {tabindex}
  lang={numOrHan === 'han' ? 'ko' : 'en'}
  style={`font-family: ${numOrHan === 'han' ? 'GowunDodum' : 'BioRhyme'}`}
>
  <slot />
</h1>

<style>
  h1 {
    font-size: clamp(1.8rem, 1.25rem + 3.3333vw, 3rem);
    min-height: 3rem;
    width: 100%;
    color: var(--gray5);
    font-weight: 700;
  }
</style>

// lib/components/styled/Goal.tsx
import styled from '@mui/system/styled';

const Goal = ({
  numOrHan,
  children,
  koreanAriaLabel,
  englishAriaLabel,
}: {
  numOrHan: 'num' | 'han';
  children: React.ReactNode;
  koreanAriaLabel: string;
  englishAriaLabel: string;
}): JSX.Element => {
  const StyledGoal = styled('h1')(({ theme }) => ({
    fontSize: 'clamp(1.8rem, 1.25rem + 3.3333vw, 3rem)',
    minHeight: '3rem',
    width: '100%',
    color: theme.palette.gray['5'],
    fontFamily: numOrHan === 'han' ? 'GowunDodum' : 'BioRhyme',
    fontWeight: '700',
  }));

  return (
    <StyledGoal
      aria-label={numOrHan === 'han' ? koreanAriaLabel : englishAriaLabel}
      tabIndex={0}
      lang={numOrHan === 'han' ? 'ko' : 'en'}
    >
      {children}
    </StyledGoal>
  );
};

export default Goal;
