// lib/components/colors/Clothing.tsx
import Pullover from './Pullover';
import Skirt from './Skirt';

// others
// https://freesvg.org/vector-line-art-drawing-of-a-simple-shirt
// https://freesvg.org/coloured-line-art-vector-image-of-trousers

export default function Clothing() {
  const colors = [0, 60, 120, 180, 240, 300];

  return (
    <>
      {colors.map(c => (
        <Skirt key={`skirt-${c}`} color={`hsl(${c}, 100%, 50%)`} />
      ))}
      {colors.map(c => (
        <Pullover key={`pullover-${c}`} color={`hsl(${c}, 100%, 50%)`} />
      ))}
    </>
  );
}

// src/lib/clothes/Clothing.svelte
<script lang="ts">
  // others
  // https://freesvg.org/vector-line-art-drawing-of-a-simple-shirt
  // https://freesvg.org/coloured-line-art-vector-image-of-trousers

  import Pullover from './Pullover.svelte';
  import Skirt from './Skirt.svelte';

  const colors = [0, 60, 120, 180, 240, 300];
</script>

{#each colors as c}
  <Skirt color={`hsl(${c}, 100%, 50%)`} />
  <Pullover color={`hsl(${c}, 100%, 50%)`} />
{/each}
