// lib/components/styled/GoalAnswer.tsx
import styled from '@mui/system/styled';

const GoalAnswer = ({
  numOrHan,
  children,
  koreanAriaLabel,
  englishAriaLabel,
  tabIndex,
}: {
  numOrHan: 'num' | 'han';
  children: React.ReactNode;
  koreanAriaLabel: string;
  englishAriaLabel: string;
  tabIndex: number;
}): JSX.Element => {
  const StyledGoalAnswer = styled('h2')(({ theme }) => ({
    fontSize: 'clamp(1.5rem, 5vw, 3rem)',
    minHeight: '4.5rem',
    color: theme.palette.gray['5'],
    fontFamily: numOrHan === 'han' ? 'GowunDodum' : 'BioRhyme',
    fontWeight: numOrHan === 'han' ? '400' : '300',
  }));

  return (
    <StyledGoalAnswer
      aria-label={numOrHan === 'han' ? koreanAriaLabel : englishAriaLabel}
      tabIndex={tabIndex}
      lang={numOrHan === 'han' ? 'ko' : 'en'}
    >
      {children}
    </StyledGoalAnswer>
  );
};

export default GoalAnswer;

// src/lib/number/components/GoalAnswer.svelte
<script lang="ts">
  export let numOrHan: 'num' | 'han';
  export let koreanAriaLabel: string;
  export let englishAriaLabel: string;
  export let tabindex = 0;
</script>

<h2
  aria-label={numOrHan === 'han' ? koreanAriaLabel : englishAriaLabel}
  {tabindex}
  lang={numOrHan === 'han' ? 'ko' : 'en'}
  style={`font-family: ${numOrHan === 'han' ? 'GoWunDodum' : 'BioRhyme'}; font-weight: ${
    numOrHan === 'han' ? '400' : '300'
  };`}
>
  <slot />
</h2>

<style>
  h2 {
    font-size: clamp(1.5rem, 5vw, 3rem);
    min-height: 4.5rem;
    color: var(--gray5);
  }
</style>
