// pages/numbers.tsx
import Head from 'next/head';
import { useState, useEffect } from 'react';
import Button from '@mui/material/Button';
import styled from '@mui/system/styled';
import { HangulNumber, NativeNumber, SinoNumber } from 'lib/number';
import { DirectionBtn, Display, HangulNumberTypeSelect, Input, RangeSlider } from 'lib/components/number';
import { VisibilitySwitch, BottomDrawer, WavePage } from 'lib/components/styled';

const Main = styled('main')({
  minHeight: '100%',
  width: '100%',
  paddingTop: '15%',
  margin: '0 auto',
  textAlign: 'center',
  display: 'flex',
  justifyContent: 'center',
  flexWrap: 'wrap',
});

const Heading = styled('h1')(({ theme }) => ({
  fontSize: '2rem',
  fontWeight: 700,
  color: theme.palette.primary.main,
}));

const Toggles = styled('div')({
  display: 'flex',
  flexWrap: 'wrap',
  width: '100%',
  justifyContent: 'space-around',
  gap: '2rem',
});

const Header = styled('header')({
  display: 'grid',
  gridTemplateColumns: '1fr',
  gridAutoFlow: 'column',
});

const SettingsBtn = styled(Button)(({ theme }) => ({
  fontFamily: 'SpaceMono',
  textTransform: 'lowercase',
  backgroundColor: theme.palette.gray['5'],
  border: `4px solid ${theme.palette.primary.main}`,
  borderRadius: '0px',
}));

export default function Numbers() {
  // state
  const [input, setInput] = useState('1');
  const [goal, setGoal] = useState<NativeNumber | SinoNumber>({} as SinoNumber);
  useEffect((): void => {
    setGoal((): NativeNumber | SinoNumber => {
      const num = HangulNumber.create('sino', 'cardinal').setRandom();
      num.range = [0, 7];
      return num;
    });
  }, []);

  // toggles
  const [showParsedInput, setShowParsedInput] = useState(false);
  const [showGoalAnswer, setShowGoalAnswer] = useState(false);
  const [drawerIsOpen, setDrawerIsOpen] = useState(false);
  const [direction, setDirection] = useState<'userNumGoalHan' | 'userHanGoalNum'>('userNumGoalHan');

  if (!goal.hangul) return null;

  return (
    <WavePage>
      <Head>
        <title>Numbers | {goal.type.replace(/^./, str => str.toUpperCase())}</title>
      </Head>
      <Header>
        <Heading>Korean Numbers</Heading>
        <SettingsBtn onClick={() => setDrawerIsOpen(true)}>Settings</SettingsBtn>
      </Header>
      <BottomDrawer isOpen={drawerIsOpen} setIsOpen={setDrawerIsOpen}>
        <HangulNumberTypeSelect goal={goal} setGoal={setGoal} />

        <RangeSlider goal={goal} setGoal={setGoal} />

        <Toggles>
          <VisibilitySwitch
            showFlag={showGoalAnswer}
            setShowFlag={setShowGoalAnswer}
            label="Answer"
            ariaLabel="Show answer"
          />

          <DirectionBtn direction={direction} setDirection={setDirection} />

          <VisibilitySwitch
            showFlag={showParsedInput}
            setShowFlag={setShowParsedInput}
            label="Input As Hangul"
            ariaLabel="Show input as hangul"
            disabled={direction !== 'userNumGoalHan'}
          />
        </Toggles>
      </BottomDrawer>
      <Main>
        <Display
          direction={direction}
          goal={goal}
          input={input}
          showGoalAnswer={showGoalAnswer}
          showParsedInput={showParsedInput}
        />

        <Input
          input={input}
          setInput={setInput}
          direction={direction}
          goal={goal}
          setGoal={setGoal}
          showParsedInput={showParsedInput}
          setShowParsedInput={setShowParsedInput}
        />
        <Toggles>
          <VisibilitySwitch
            showFlag={showGoalAnswer}
            setShowFlag={setShowGoalAnswer}
            label="Answer"
            ariaLabel="Show answer"
          />

          <DirectionBtn direction={direction} setDirection={setDirection} />
        </Toggles>
      </Main>
    </WavePage>
  );
}

// src/routes/numbers/index.svelte
<script lang="ts">
  import DirectionBtn from '$common/components/ButtonLanguageDirection.svelte';
  import { direction, drawer, showGoalAnswer, showParsedInput, hint } from '$number/stores';
  import WavePage from '$common/components/WavePage.svelte';
  import { goal } from '$number/stores';
  import Display from '$lib/number/components/Display.svelte';
  import VisibilitySwitch from '$common/components/VisibilitySwitch.svelte';
  import Input from '$number/components/Input.svelte';
  import Drawer from '$common/components/Drawer.svelte';
  import HangulNumberTypeSelect from '$number/components/HangulNumberTypeSelect.svelte';
  import RangeSlider from '$lib/number/components/RangeSlider.svelte';
  import { browser } from '$app/env';

  if (browser) {
    document.onkeydown = e => {
      if (e.key === 'Escape') {
        drawer.close();
      }
    };
  }
</script>

<svelte:head>
  <title>Numbers | {$goal.type.replace(/^./, str => str.toUpperCase())}</title>
  <link rel="icon" href="/favicon.svg" />
</svelte:head>

<WavePage shimmer={$drawer}>
  <header>
    <h1>Korean Numbers</h1>

    <button class="settingsBtn" on:click={drawer.toggle}> Settings </button>
  </header>

  <main style={`filter: ${$drawer ? 'var(--shimmer)' : ''}`}>
    <Display />
    <!-- ariaLabel={$direction === 'userHanGoalNum' ? 'change to number input' : 'change to hangul input'} -->

    <Input />
    <div class="togglesContainer">
      <VisibilitySwitch bind:checked={$showGoalAnswer} label="answer" labelPosition="right" size="lg" />
      <p class="hint">{$hint ?? ' '}</p>
      <DirectionBtn
        on:click={direction.toggle}
        direction={$direction === 'userHanGoalNum' ? 'left' : 'right'}
        labelLeft="한글"
        labelRight="123"
      />
    </div>
  </main>

  <Drawer {drawer} selectorsImmuneToClickOutside={['.settingsBtn']}>
    <div class="drawer-topbar">
      <h1>Settings</h1>
      <button on:click={() => drawer.close()}>Close</button>
    </div>

    <div class="select-positioner">
      <HangulNumberTypeSelect />
    </div>
    <RangeSlider />

    <div class="drawer-toggles">
      <VisibilitySwitch label="answer" labelPosition="right" bind:checked={$showGoalAnswer} />
      <DirectionBtn
        on:click={direction.toggle}
        direction={$direction === 'userHanGoalNum' ? 'left' : 'right'}
        labelLeft="한글"
        labelRight="123"
      />
      <VisibilitySwitch label="Input as Hangul" labelPosition="right" bind:checked={$showParsedInput} />
    </div>
  </Drawer>
</WavePage>

<style>
  header {
    display: grid;
    grid-template-columns: 1fr;
    grid-auto-flow: column;
  }
  h1 {
    font-size: 2rem;
    font-weight: 700;
    color: var(--primary2);
  }
  .settingsBtn {
    font-family: SpaceMono;
    text-transform: lowercase;
    background-color: var(--gray5);
    border: 4px solid var(--primary2);
    border-radius: 0px;
    padding: 0.5rem;
    font-size: 1rem;
    color: var(--primary2);
  }
  main {
    padding-top: 15%;
    display: grid;
    place-items: center;
    text-align: center;
  }
  .togglesContainer {
    display: grid;
    grid-template-columns: 1fr 1fr;
    grid-template-rows: 1fr 1fr;
    place-content: center;
    width: 100%;
    gap: 2rem;
  }
  .togglesContainer :global(*) {
    display: grid;
    justify-content: center;
  }
  .hint {
    display: grid;
    place-content: center;
    color: var(--secondary5);
    height: 3rem;
    font-size: 0.75rem;
  }
  @media only screen and (min-width: 600px) {
    .hint {
      font-size: 1rem;
    }
  }
  @media only screen and (min-width: 800px) {
    .hint {
      font-size: 1.5rem;
    }
    .togglesContainer {
      grid-template-columns: repeat(3, 1fr);
    }
  }
  .select-positioner {
    padding-top: 1rem;
    text-align: center;
  }
  .drawer-topbar {
    padding: 0.5rem 1rem;
    display: grid;
    gap: 1rem;
    grid-template-columns: 1fr;
    grid-auto-flow: column;
    align-items: baseline;
    margin: 0 1rem;
    padding: 1rem 1.5rem 0.5rem 1.5rem;
    border-bottom: 0.5px solid rgba(0, 0, 0, 0.2);
  }
  .drawer-topbar h1 {
    font-size: 2rem;
    font-weight: 700;
    color: var(--secondary1);
  }
  .drawer-topbar button {
    font-size: 1rem;
    color: var(--secondary1);
    text-transform: uppercase;
  }
  .drawer-toggles {
    display: grid;
    grid-template-columns: repeat(3, 1fr);
    place-items: center;
  }
  @media only screen and (max-width: 800px) {
    .drawer-toggles {
      display: flex;
      flex-wrap: wrap;
      justify-content: space-around;
      gap: 1rem;
    }
  }
</style>
